### ISSUE TITLE
Bad HTTP request, 400

### ISSUE THREAD

**Issue by alanoatwork** [sstrickx/yahoofinance-api#77] opened 2017-05-24 02:10 UTC
Here's when I get when I try to retrieve ^GSPC using 3.7.0.
```
May 23, 2017 5:55:07 PM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: N/A,\"^GSPC\",N/A,\"SNP\",2420.21,N/A,\"^GSPC\",N/A,\"^GSPC\",2368.95,N/A,\"^GSPC\",N/A,\"^GSPC\",2398.42,\"^GSPC\",N/A,\"^GSPC\",\"5/23/2017\",\"4:38pm\",2397.04,2394.02,2393.88,2400.85,1770956038,N/A,2405.77,1991.68,N/A,N/A,\"^GSPC\",N/A,\"^GSPC\",\"^GSPC\",N/A,\"^GSPC\",N/A,\"^GSPC\",N/A,\"^GSPC\",N/A,N/A,N/A,N/A,N/A,N/A,0.00,N/A,N/A,0.00,N/A,N/A,0.00,N/A,N/A,N/A,N/A
May 23, 2017 5:55:08 PM yahoofinance.histquotes2.HistQuotes2Request getResult
INFO: Sending request: https://query1.finance.yahoo.com/v7/finance/download/^GSPC?period1=1495756800&period2=1497830400&interval=1d&crumb=04M%2FiEkVllu
java.io.IOException: Server returned HTTP response code: 400 for URL: https://query1.finance.yahoo.com/v7/finance/download/^GSPC?period1=1495756800&period2=1497830400&interval=1d&crumb=04M%2FiEkVllu
```

**Comment by sstrickx** [comment] 2017-05-24 07:56
There's probably an issue because I didn't URL-escape the ticker properly when building the request URL. 
Will try to fix it ASAP, but I'm quite busy until tomorrow afternoon.

**Comment by sstrickx** [comment] 2017-05-26 20:50
I didn't manage to reproduce the problem (could be related to the Java version being used).
Anyway, I just released version 3.8.0 in which the URL should be escaped properly.
If this doesn't resolve the issue for you, could you tell me which Java version you're using?

**Comment by olodanderfluff** [comment] 2017-05-30 12:52
(sorry, I'm not familiar with english)
I also experienced the same issue. (Bad HTTP request, 400)
My issue is related data availability.
Please test: 
1) Bad Reqeust 400 error <=== 'AREX', '2001-01-10', '2005-12-31'
2) Success        <=== 'AREX', '2012-01-10', '2013-12-31'

so, i think that this (excellent) library has no problem.
but error message/handling could be improved.

**Comment by sstrickx** [comment] 2017-06-02 20:30
@olodanderfluff: Thanks! That helped a lot.
It seems like this is indeed the same problem.
Looking into more detail at the logs of @alanoatwork it is now clear that this was a request on 2017-05-24 to retrieve historical data between 2017-05-26 and 2017-06-19. Obviously there was no data available from the future and Yahoo Finance returned a 400 error.
Same goes for your request on AREX. The first historical data point that seems to be available is on 2007-11-08. Any range that ends before this date will result in a 400 error as well.

It is indeed a case where error handling needs to be improved. 
I'll close this and make a reference to #68.

**Closed by sstrickx** 2017-06-02 20:30 UTC
