### ISSUE TITLE
Utilsjava throws Unparseable date exception for the symbol -> JCP

### ISSUE THREAD

**Issue by jbdundas** [sstrickx/yahoofinance-api#2] opened 2015-01-25 12:22 UTC
IT looks like it is giving an Unparseable exception for JCP.

I am trying to fetch the DividendYield detaills and it seems to come when it tries to parse the dividend date. I tried to use the trim() but it still fails.
Jan 25, 2015 7:21:36 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Sending request: http://finance.yahoo.com/d/quotes.csv?s=JCP&f=n0sc4x0a0b2sa5sb0b3sb6sl1sk3sd1t1o0p0g0h0v0a2k0j0m3m4sj2sss1sj1sf6sr1q0d0y0e0e7e9e8r0r5p6p5b4s6j4t8&e=.csv
Jan 25, 2015 7:21:37 AM yahoofinance.quotes.QuotesRequest getResult
INFO: Parsing CSV line: \"J.C. Penney Compa\",\"JCP\",\"USD\",\"NYSE\",N/A,7.75,\"JCP\",N/A,\"JCP\",N/A,6.75,\"JCP\",N/A,\"JCP\",7.52,\"JCP\",N/A,\"JCP\",\"1/23/2015\",\"4:01pm\",7.50,7.49,7.38,7.58,6920662,16251600,11.30,4.90,6.9094,8.43,\"JCP\",   304,851,000,\"JCP\",\"JCP\",-,\"JCP\",2.292B,\"JCP\",   290,676,000,\"JCP\",\" 1-May-12\",\" 5-Apr-12\",0.00,N/A,-2.219,-2.54,-0.72,-1.36,N/A,0.11,0.94,0.19,7.972,12.146B,30.0M,8.22
Jan 25, 2015 7:21:37 AM yahoofinance.Utils parseDividendDate
SEVERE: Unparseable date: "1-May-12"
java.text.ParseException: Unparseable date: "1-May-12"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at yahoofinance.Utils.parseDividendDate(Utils.java:124)
	at yahoofinance.quotes.stock.StockQuotesData.getDividend(StockQuotesData.java:87)
	at yahoofinance.Stock.update(Stock.java:44)
	at yahoofinance.Stock.getStats(Stock.java:126)
	at yahoofinance.Stock.getStats(Stock.java:104)
	at com.jnd.stocksparser.StockAnalysisBatchClass.processBuffetRating(StockAnalysisBatchClass.java:80)
	at com.jnd.stocksparser.StockAnalysisBatchClass.main(StockAnalysisBatchClass.java:241)

Jan 25, 2015 7:21:37 AM yahoofinance.Utils parseDividendDate

Thanks,
JItesh

**Comment by sstrickx** [comment] 2015-01-25 18:58
Duplicate of #4

**Closed by sstrickx** 2015-01-25 18:58 UTC
